{
 "title": "Task Processing System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Task Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Task Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(task_status{}[1m])", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Task Process Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(task_processing_duration_bucket[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(task_processing_duration_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(task_processing_duration_bucket[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Task Processing Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(task_processing_success_count_total{}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(task_processing_fail_count_total{}[1m])",
     "legendFormat": "Fail"
    }
   ]
  },
  { "title": "Task API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Create Task API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(task_create_request_count_total{}[1m])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(task_create_success_count_total{}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(task_create_fail_count_total{}[1m])",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Get Task API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(task_get_request_count_total{}[1m])",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Cancel Task API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(task_cancel_request_count_total{}[1m])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(task_cancel_success_count_total{}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(task_cancel_fail_count_total{}[1m])",
     "legendFormat": "Fail"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "queue_length{}", "legendFormat": "Length" }
   ]
  },
  {
   "title": "Queue Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(queue_push_count_total{}[1m])",
     "legendFormat": "Push"
    },
    {
     "expr": "rate(queue_push_fail_count_total{}[1m])",
     "legendFormat": "Push Fail"
    },
    {
     "expr": "rate(queue_pop_count_total{}[1m])",
     "legendFormat": "Pop"
    },
    {
     "expr": "rate(queue_pop_fail_count_total{}[1m])",
     "legendFormat": "Pop Fail"
    }
   ]
  }
 ]
}